### ISSUE TITLE
Fetch Request: ferris-fetch

### ISSUE THREAD

**Issue by irevenko** [TorchedSammy/fetches#3]
yes this is my fetch 🦀
 [![GitHub stars](https://img.shields.io/github/stars/irevenko/ferris-fetch?style=social)](https://github.com/irevenko/ferris-fetch/stargazers/)
https://github.com/irevenko/ferris-fetch

**Comment by TorchedSammy** [comment]
can you pr it? I'm currently without any computer and don't want to setup git on termux

**Comment by TorchedSammy** [comment]
actually i am on my pc now, ill add it in a bit

**Comment by irevenko** [comment]
PR'ed: https://github.com/TorchedSammy/fetches/pull/4 🎉
